#!/usr/bin/env zsh

# steps before we run this:
# 1. open browser and log into github, go to the dots repo
# 2. download this file from .local/bin
# 3. ssh-keygen and upload key to github

# This script should ideally just be used once.
# Subsequent runs will only update the submodules and install any packages newly added to the flake.

echo "Starting bootstrap process..."

install_cmd="apt install"
packages="libssl-dev python3 python3-pip libsecret-tools lua5.4 libplayerctl2-dev playerctl cmake libwayland-dev libpam libxcb-cursor-dev iwd bison flex udiskie xournal powertop libfuse2t64 libfuse3-dev"
system="debian"
if type "apt" >/dev/null; then
  install_cmd="apt install"
  system="debian"
elif type "pacman" >/dev/null; then
  install_cmd="pacman -S"
  system="arch"
  # TODO: Add a list corresponding to arch here. We want to install broadly the same set of software in Arch. Since Arch
  # probably has the latest software already, we might not need nix involved at all.
  # It is generally easier to maintain software using the system's package manager.
fi

sudo apt install git

confirmation="n"
while true; do
  if read -q "choice?Have you registered the ssh key on GitHub? (y/n): "; then break; else echo; fi
done

mkdir -p $HOME/.local/opt/git
mkdir -p $HOME/.local/opt/apps
alias dots='/usr/bin/git --git-dir=$HOME/.local/opt/dots/ --work-tree=$HOME'

# initialise dotfiles
if [ -d "$HOME/.local/opt/dots" ]; then
  dots pull --autostash
else
  git clone --bare git@github.com:adwaymalhotra/dots.git $HOME/.local/opt/dots
  dots config remote.origin.fetch +refs/heads/main:refs/remotes/origin/main
  dots config remote.origin.rebase main
  dots config branch.main.remote origin
  dots config branch.main.merge refs/heads/main

  mkdir -p .config-backup &&
    dots checkout 2>&1 | egrep "\s+\." | awk {'print $1'} |
    xargs -I{} mv {} .config-backup/{}
  dots reset --hard
fi
source ~/.zshrc

# initialise fonts, zmk, zmk_batt and flake submodules
dots submodule update --init
fc-cache -f

sudo $install_cmd $packages

if [ ! $system=="arch" ]; then
  [ ! -d "/nix" ] &&
    yes | NIX_FIRST_BUILD_UID=50000 NIX_BUILD_GROUP_ID=50000 sh <(curl -L https://nixos.org/nix/install) --daemon

  nix profile install $HOME/.local/opt/packages-flake
fi

loginctl enable-linger $USER
set-theme mellow

# install rust automatically
[ ! -d "$HOME/.cargo" ] &&
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
